### ISSUE TITLE
Item Removal

### ISSUE THREAD

**Issue by TlYPN** [Brazzers-Development/brazzers-harness#1]
Harness's dont seem to actually be removed when used and applied to a vehicle

**Comment by Jackster-2233** [comment]
I have the same issue, having to update the harness field manually to true in the DB

**Comment by MannyOnBrazzers** [comment]
At the bottom of the readme, you must change the useable item event for the harness item in qb-smallresources > main.lua. Please fully read the readme!

**Comment by MannyOnBrazzers** [comment]
This resolved @Jackster-2233 issue!
