### ISSUE TITLE
Harness persistence doesn't work with custom plates.

### ISSUE THREAD

**Issue by LukeeeChan** [Brazzers-Development/brazzers-harness#2]
When you update the plate in-game via an item or admin menu, harness persistence on the vehicle disappears.

**Comment by MannyOnBrazzers** [comment]
I'll take a look at this issue, allow me a couple days

**Comment by DannysRP** [comment]
I can confirm it does not work with custom plates I believe. Or if the plate is under 8 characters it doesn't work

**Comment by DannysRP** [comment]
Double checked. It seems to only work for plates that are 7-8 characters. Anything under that it doesn't work

**Comment by DannysRP** [comment]
> I'll take a look at this issue, allow me a couple days

Get a chance to check this out yet?

**Comment by IngleArf** [comment]
Has this issues been looked at yet?

**Comment by ayushabhinav-dev** [comment]
@LukeeeChan @IngleArf @DannysRP i have made the pull request you can check it
